### ISSUE TITLE
VHT Not working properly need assistance.

### ISSUE THREAD

**Issue by FredVeldini** [cozybit/authsae#103]
Im trying to get VHT on Authsae (Latest Version Downloaded 12-7-18) with no luck, maybe someone could assist.
I have 2 Atheros QCA988x 802.11ac Wireless Network Adapters, one in each computer.
I'm running Kernel 4.19.0-wt from wireless-testing.
I have the latest ath10k firmware from Kvalo git

Radios show up properly
startup is same as before
iw dev mesh0 set freq 5180 80 5210
then start mesh 
---------------------
authsae.conf is pretty straight forward.
---------------------
authsae:
{
sae:
{
debug = 480;
password = "SuperSecretPassw0rd";
group = [19, 26, 21, 25, 20];
blacklist = 5;
thresh = 5;
lifetime = 3600;
};
meshd:
{
meshid = "MESH0LVL";
interface = "mesh0";
band = "11a";
channel = 36;
htmode = "VHT80";
mcast-rate = 12;
};
};
------------------------
Radio shows 80MHz is working properly - iw dev mesh0 info
Interface mesh0
	ifindex 12
	wdev 0x2
	addr 00:30:1a:4e:3d:af
	type mesh point
	wiphy 0
	channel 36 (5180 MHz), width: 80 MHz, center1: 5210 MHz
	txpower 10.00 dBm
	multicast TXQ:
		qsz-byt	qsz-pkt	flows	drops	marks	overlmt	hashcol	tx-bytes	tx-packets
		124	1	144239	0	0	0	0	19450068		284665

--------------------
But as you see below the iw dev mesh0 station dump shows HT40
Station 00:30:1a:4e:2a:01 (on mesh0)
	inactive time:	181 ms
	rx bytes:	410098580
	rx packets:	538216
	tx bytes:	397003042
	tx packets:	345115
	tx retries:	0
	tx failed:	4
	rx drop misc:	131712
	signal:  	-52 [-63, -63, -57] dBm
	signal avg:	-53 [-62, -62, -56] dBm
	Toffset:	18446744073680841152 us
	tx bitrate:	243.0 MBit/s MCS 20 40MHz
	rx bitrate:	360.0 MBit/s MCS 21 40MHz short GI
	rx duration:	0 us
	mesh llid:	0
	mesh plid:	0
	mesh plink:	ESTAB
	mesh local PS mode:	ACTIVE
	mesh peer PS mode:	ACTIVE
	mesh non-peer PS mode:	ACTIVE
	authorized:	yes
	authenticated:	yes
	associated:	yes
	preamble:	long
	WMM/WME:	yes
	MFP:		yes
	TDLS peer:	no
	DTIM period:	2
	beacon interval:1000
	connected time:	30486 seconds
-------------------
Throughput with iperf3 is an average of 275 Mbps
Any help on getting VHT working would be appreciated.

Fred

**Comment by bcopeland** [comment]
On Sat, Dec 08, 2018 at 07:07:13AM -0800, FredVeldini wrote:
> Im trying to get VHT on Authsae with no luck, maybe someone could assist.
> I have 2 Atheros QCA988x 802.11ac Wireless Network Adapters, one in each computer.
> I'm running Kernel 4.19.0-wt from wireless-testing.
> I have the latest ath10k firmware from Kvalo git
>
> htmode = "VHT80";

Check tests/test008.sh for how to configure it.  Namely, you'll need to
specify it like this:

    channel_width = "80";
    freq  = 5180;
    center_freq1 = 5210;

"htmode" is not specific enough to configure the proper center channel
for all modes.  Also make sure you have the very latest authsae.

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by FredVeldini** [comment]
Thanks Bob,
I noticed in the include.sh file the htmode="none"
is that correct.

**Comment by bcopeland** [comment]
On Sat, Dec 08, 2018 at 08:38:17AM -0800, FredVeldini wrote:
> Thanks Bob,
> I noticed in the include.sh file the htmode="none"
> is that correct.

test008 removes the htmode line entirely, you should also leave it out.

-- 
Bob Copeland %% https://bobcopeland.com/

**Comment by FredVeldini** [comment]
Thank you Bob,
Works great now.  (removed htmode for VHT - and added the channel information did the job)
	tx bitrate:	975.0 MBit/s VHT-MCS 7 80MHz short GI VHT-NSS 3
	rx bitrate:	975.0 MBit/s VHT-MCS 5 80MHz short GI VHT-NSS 3
Throughput averaging around 450Mbits/sec
Thank you again.
Fred
