### ISSUE TITLE
segfault in debug mode, level 0x10 (SAE_DEBUG_CRYPTO_VERB)

### ISSUE THREAD

**Issue by jkogels** [cozybit/authsae#19]
Hello,
Currently I try to secure a mesh network with SAE. With the meshd-80211 is seems to getting up and running, although some issue araised.
One is a segmentation fault when trying to debug the crypto on verbose level. I checked also this setting on openwrt, and it has the same behaviour.

Segmentation fault when starting meshd-80122 in debug mode, level 0x10 (SAE_DEBUG_CRYPTO_VERB, from authsae/common.h).
After this error the meshd stops:
The syslog:
Dec  7 10:17:25 AHR-175-101 vmunix: [348301.778513] meshd-nl80211[23719]: segfault at 34f6cf74 ip b7440b3a sp bff20fec error 4 in libc-2.13.so[b73d1000+149000]

The config file for meshd-80211: ("/usr/local/etc/authsae.cfg" 23L, 359C)
/* this is a comment */
authsae:
{
 sae:
  {
    debug = 16;
    password = "12345678901234567890";
    group = [19, 26, 21, 25, 20];
    blacklist = 5;
    thresh = 5;
    lifetime = 3600;
  };
 meshd:
  {
    meshid = "owrt_mesh";
    interface = "wlan0";
    band = "11g";
    channel = 11;
    htmode = "none";
    mcast-rate = 12;
  };
};

Kernel info:
Uname -a:
Linux AHR-175-101 4.2.6-486 #1 SMP Sun Nov 29 19:47:56 CET 2015 i686 GNU/Linux

Source code:
Github ref: https://github.com/cozybit/authsae.git

Info on the OpenWRT distro can be provided if required.

Kind regards,
Jeffrey

**Comment by bcopeland** [comment]
Hmm, well, it would help to get a core file or at least get the addresses resolved to line numbers.

That said, these days you should probably be using wpa_supplicant to run a secure mesh.

**Comment by jkogels** [comment]
Thanks for your reply.
Do you mean the core dump file? That one is not created, last lines logged are "segfault at.."
The meshd-80211 will crash in several seconds. So I can fetch some info from strace if it's helpfull? The fault is very easy to reproduce, just set the debug level in the authsae.cfg to 16.

Other issue is a mem leakage, after a while the proces has allocated all the mem available. 

I like your suggestion to use an other way to secure the mesh, wpa_supplicant.
Regarding this suggestion to use wpa_supplicant, it does raise some questions.
What is the advantage of using wpa_supplicant versus the authsae daemon for secure mesh? And is it well supported and maintained in the github?

At least I will setup a config of the wpa_supplicant on my current meshd hardware.
I found your article on wpa_supplicant : https://bobcopeland.com/blog/2014/09/wpas-mesh/
A good start for setting up the wpa_supplicant.

Kind regards,
Jeffrey

**Comment by bcopeland** [comment]
Yes, if you could get a core dump file that would be useful (try `ulimit -c unlimited`) or a backtrace (run mesh inside gdb, and do `bt` once the segfault occurs).  I'll try your debug level shortly.

wpa_supplicant is probably better supported than authsae at this point.  It is maintained inside the upstream hostapd repository (see https://w1.fi/), so use that instead of any github trees you may find.

**Comment by alexgrin** [comment]
Jeffrey, you can also try running authsae via strace for a quick glance at what's going on - "strace -v meshd-80211 -c <your.conf>" I'll try to run with your config as well shortly.

**Comment by alexgrin** [comment]
I tracked down the explosion to debug print that was trying to put data into NULLed print buffer, see the pull request above. My local build stopped breaking with the patch applied.

**Comment by jkogels** [comment]
Pulled the latest master with the merged fix in it, this is running oke now! Thanks for the fast response and fix. 
Jeffrey
