### ISSUE TITLE
"correct token received" logged as errors, should be a debug level

### ISSUE THREAD

**Issue by tecoboot** [cozybit/authsae#32]
In a somewhat larger network, lots of "correct token received" errors are logged. This seems to me that there is no problem. Maybe change debug level to SAE_DEBUG_STATE_MACHINE instead of SAE_DEBUG_ERR?

**Comment by fhuberts** [comment]
this was fixed by e80a126f27cf4fdd7d15a56750db091496bbda64

can be closed
