### ISSUE TITLE
Unexpected error -22 (expected -17), nlerror, cmd 0, seq 1461249716: Invalid argument

### ISSUE THREAD

**Issue by crazy4chrissi** [cozybit/authsae#34]
I get this error when I join the mesh with the second node:

`Unexpected error -22 (expected -17)`

I guess this is a NLE_MSGTYPE_NOSUPPORT from libnl? How can I find out what the msgtype is that is not supported?

I also see this error:
```
joining mesh MESH2 on freq 2462, mode 0
nlerror, cmd 0, seq 1461249716: Invalid argument
```

The nodes see each other in "iw mesh0 station dump", but they can't communicate over IP (no ping, Destination Host Unreachable) and "iw mesh0 mpath dump" ouputs zero MAC address as next hop:

```
DEST ADDR         NEXT HOP          IFACE	SN	METRIC	QLEN	EXPTIME		DTIM	DRET	FLAGS
7c:dd:90:XX:XX:XX 00:00:00:00:00:00 mesh0	0	0	0	0	1600	4	0x0
```

I tried on Arch Linux and Ubuntu Linux.

Any ideas? Is authsae ready to be used for 802.11s encryption at all under Linux? I know the readme says it isn't, but the readme also hasn't been updated for years, so I though I'd give it a try...

**Comment by chunyeow** [comment]
What hardware you use? Which driver?

**Comment by crazy4chrissi** [comment]
This is lsusb's output:
```
Bus 001 Device 005: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
```
An open mesh works fine with these adapters.

**Comment by chunyeow** [comment]
Load the driver with nohwcrypt=1 and make sure the following patch is
applied:
http://www.spinics.net/lists/linux-wireless/msg150016.html

---
Chun-Yeow

**Comment by crazy4chrissi** [comment]
Thanks for the quick reply, I will try it.

**Comment by crazy4chrissi** [comment]
Thanks a lot. I patched the rt2800usb module and loaded it with nohwcrypt=1 on both the Ubuntu and Arch system and now it works. :)
