### ISSUE TITLE
no rssi_threshold config with authsae

### ISSUE THREAD

**Issue by jmpsystems** [cozybit/authsae#44]
rssi_threshold config does effective without authsae.
but with authsae it does not effective.
anyone solved this issue?

**Comment by chunyeow** [comment]
It is not supported using authsae since the peering management is managed
by authsae. You can enhance the code to support this.

**Comment by bcopeland** [comment]
In recent kernels, the mesh_rssi_threshold mesh param does affect which new peer candidate events are delivered to userspace, so you can use `iw` to set it.
