### ISSUE TITLE
meshd-nl80211 5GHz not working

### ISSUE THREAD

**Issue by interpretor** [cozybit/authsae#60]
Authsae doesn't work for me in the 5GHz frequency. I get the following nlerror at startup:
```
joining mesh samplemesh on freq 5180, mode 3
nlerror, cmd 68, seq 1493191664: Invalid argument
```
I don't find any error in the code, and the nlerror doesn't tell me much. It looks like the payload data is coming from `struct genlmsghdr *gnlh = nlmsg_data(&err->msg);`

In unencrypted mesh, the 5GHz channels work just fine with HT20, HT40- and HT40+ enabled.
Encrypted mesh with 2.4GHz also works just fine.

Used Chipset: RT5370 and RT5572, nohwcrypt flag set to 1, Kernel 4.9
Any ideas?

**Comment by chunyeow** [comment]
If it is Ralink chipset, try to load the driver with "nohwcrypt=1".

**Comment by interpretor** [comment]
I am already using the nohwcrypt=1 flag, it is working in the 2.4GHz Band.
The config that works:
```
authsae:
{
 sae:
  {
    debug = 480;
    password = "thisisreallysecret";
    group = [19, 26, 21, 25, 20];
    blacklist = 5;
    thresh = 5;
    lifetime = 3600;
  };
 meshd:
  {
    meshid = "mesh";
    interface = "mesh0";
    band = "11g";
    channel = 6;
    htmode = "HT20";
    mcast-rate = 12;
  };
};
```
The config that does NOT work:
```
authsae:
{
 sae:
  {
    debug = 480;
    password = "thisisreallysecret";
    group = [19, 26, 21, 25, 20];
    blacklist = 5;
    thresh = 5;
    lifetime = 3600;
  };
 meshd:
  {
    meshid = "pi2p5";
    interface = "mesh0";
    band = "11a";
    channel = 36;
    htmode = "HT20";
    mcast-rate = 12;
  };
};
```
With the second configuration the peers will not connect and it gives the error that I posted above.

**Comment by chunyeow** [comment]
RT5370 is bgn
RT5572 is abgn 

So only RT5572 has 5GHz support. Confirm that this is not the issue?

**Comment by interpretor** [comment]
I use the 5GHz mesh only on the RT5572 chipsets, so no, this can't be the issue.

**Comment by chunyeow** [comment]
Can you confirm whether the interface allows adhoc mode on the 5GHz or not?
* 5180 MHz [36] (17.0 dBm) (passive scanning, no IBSS)

Use "iw phyX info" to check.

**Comment by interpretor** [comment]
Thank you very much for the hint, I just forgot to set the correct region in iw.
Looks like everything is working now.
Just wondering why the unencrypted mesh will set up with wrong region settings...
