### ISSUE TITLE
Krack attack

### ISSUE THREAD

**Issue by acksys** [cozybit/authsae#61]
Do you know if authsae daemon is concerned by this attack?

**Comment by PacoBell** [comment]
It should not as KRACK applies to WPA, not SAE. Nevertheless, these kinds of protocol-level wake-up calls should definitely prompt the authsae maintainers to introspect their code designs with a fine-toothed comb to ensure they don't also succumb to a similar failure.

**Comment by acksys** [comment]
Thanks for your reply. I'm waiting an answer from the maintener.

**Comment by bcopeland** [comment]
My understanding is, as presented, no, because there is no 4-way handshake in SAE which is what this attack relies on.  However, I haven't studied it enough to know if there's not a related flaw in SAE.

**Comment by bcopeland** [comment]
I looked into AMPE and we only install the keys after reaching ESTAB state, once there we won't install any more keys until the peering is broken.  When peering is broken, we recreate the AEK and all other keys in the key hierarchy in `peer_ampe_init` and the MTK will get a new random nonce, so I do not see a way to perform a key reinstallation attack.  This of course is not an official security audit, just my 2 cents.  I'll close this as there's nothing actionable at this time.
