### ISSUE TITLE
Little helps in building?? 

### ISSUE THREAD

**Issue by e1001925** [cozybit/authsae#63]
Dear authsae team,

Hi! Could anybody kindly help provide more details about "Edit the Makefile to point $(LIBS) to OpenSSL and make" in **ReadMe**? Since I cannot find $(LIBS)....

I am not familiar with cmake, but to my understanding, what I need to do is link libcrypto and libconfig in authsae/CMakeLists.txt.. Is this right?

Any comments or examples is greatly appreciated~~

**Comment by e1001925** [comment]
By the way, since my  openssl seems don't have a cmakelist.txt. So I am suppose to write for it? Its just so much pain....

**Comment by e1001925** [comment]
And why libconfig cannot be found... I kind of stuck here..

**Comment by bcopeland** [comment]
On Thu, Mar 22, 2018 at 03:41:51AM +0000, Michael65535 wrote:
> And why libconfig cannot be found... I kind of stuck here.. 

You'll have to install the development package for libconfig,
along with pkg-config on your build host.  The dev packages
for openssl (libcrypto) and libconfig on debian both have
pkg-config files.

**Comment by e1001925** [comment]
Hi @bcopeland , It works !!!!!! 

Thanks so much for your valuable suggestions.

And I have one more question, since I need to burn it into a cutdown linux system and run as a daemon, like put some execute file into bin. However, after make, my authsae/build is still empty. Any idea what execute file should I use?

**Comment by bcopeland** [comment]
On Fri, Mar 23, 2018 at 07:07:45AM +0000, Michael65535 wrote:
>  Hi @bcopeland , It works !!!!!! 
> 
> Thanks so much for your valuable suggestions.
> 
> And I have one more question, since I need to burn it into a cutdown linux system and run as a daemon, like put some execute file into bin. However, after make, my authsae/build is still empty. Any idea what execute file should I use? 

Normally the output artifact you want is `build/linux/meshd-nl80211`.

**Comment by e1001925** [comment]
Hi @bcopeland , strangely my build folder is always empty.

After I use make, I get following message:
"
[ 31%] Built target sae
[ 50%] Built target mon
[ 81%] Built target meshd
[100%] Built target meshd-nl80211
" 

There is no error message showed. I have no clue.. Could u please help me out?

**Comment by e1001925** [comment]
Ok I get it. The path is /authsae/linux/meshd-nl80211..

Now the problem is I need MIPS version....

**Comment by e1001925** [comment]
Hi @bcopeland , could you please provide a link?

Sorry I did some searching and really cannot google it out. Do you mean the OpenWRT in full? That one I saw mips options..

I have a bad feeling that I may need to rewrite a makefile myself which is very very difficult...

**Comment by bcopeland** [comment]
If you are building binaries for MIPS AP targets, you will generally be using a cross-toolchain, or something like buildroot / yocto / OpenWRT.  It's a bit beyond the scope of this project to say how to do that because all of those kinds of systems have their own ways of incorporating third party projects, but usually it is just a matter of telling those build systems where to get the source code and that authsae uses CMake.

We've updated the build instructions in the README recently.
